[platformio]
default_envs = tx, rx

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=0

[env:tx]
build_src_filter =
  +<tx_main.cpp>

[env:rx]
build_src_filter =
  +<rx_main.cpp>
